// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8eZTM3qkGcFpIPIy5b29dsj_13pvGkQU',
    appId: '1:263576703167:web:a960155a43f81c03a3760a',
    messagingSenderId: '263576703167',
    projectId: 'ecoruta-app-f3925',
    authDomain: 'ecoruta-app-f3925.firebaseapp.com',
    storageBucket: 'ecoruta-app-f3925.firebasestorage.app',
    measurementId: 'G-J38VQ50FJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6SUmxrNKkTkoXJ6NMDJ2SCmzkmY5fzA',
    appId: '1:263576703167:android:d71133147070f1fda3760a',
    messagingSenderId: '263576703167',
    projectId: 'ecoruta-app-f3925',
    storageBucket: 'ecoruta-app-f3925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0gkG-xW3ZfhP1fB3KvwKTjIcMEc2l5A',
    appId: '1:263576703167:ios:44a6eaab3c06754ca3760a',
    messagingSenderId: '263576703167',
    projectId: 'ecoruta-app-f3925',
    storageBucket: 'ecoruta-app-f3925.firebasestorage.app',
    iosClientId: '263576703167-abockot6m5r0oam30lj6kf0netp09koo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoruta1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM0gkG-xW3ZfhP1fB3KvwKTjIcMEc2l5A',
    appId: '1:263576703167:ios:44a6eaab3c06754ca3760a',
    messagingSenderId: '263576703167',
    projectId: 'ecoruta-app-f3925',
    storageBucket: 'ecoruta-app-f3925.firebasestorage.app',
    iosClientId: '263576703167-abockot6m5r0oam30lj6kf0netp09koo.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoruta1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8eZTM3qkGcFpIPIy5b29dsj_13pvGkQU',
    appId: '1:263576703167:web:c6eb47e52518e0ffa3760a',
    messagingSenderId: '263576703167',
    projectId: 'ecoruta-app-f3925',
    authDomain: 'ecoruta-app-f3925.firebaseapp.com',
    storageBucket: 'ecoruta-app-f3925.firebasestorage.app',
    measurementId: 'G-REXN0648CW',
  );
}
